# Generated by Django 3.0.4 on 2020-03-18 15:17

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_data',
            field=models.DateField(blank=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=10, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2,3}-\\d{3,4}-\\d{4}$', '-와 12자 이하의 숫자만 사용합니다', 'invalid phone_number')], verbose_name='휴대폰 번호'),
        ),
    ]
