# Generated by Django 3.0.4 on 2020-03-18 15:19

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200319_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_data',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='account',
            name='building_id',
            field=models.CharField(max_length=30, null=True, verbose_name='건물번호'),
        ),
        migrations.AlterField(
            model_name='account',
            name='detail_address',
            field=models.CharField(max_length=200, null=True, verbose_name='상세주소'),
        ),
        migrations.AlterField(
            model_name='account',
            name='eup_myun_dong',
            field=models.CharField(max_length=30, null=True, verbose_name='읍면동명'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lee',
            field=models.CharField(max_length=30, null=True, verbose_name='법정리명'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=10, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2,3}-\\d{3,4}-\\d{4}$', '-와 12자 이하의 숫자만 사용합니다', 'invalid phone_number')], verbose_name='휴대폰 번호'),
        ),
        migrations.AlterField(
            model_name='account',
            name='road_name',
            field=models.CharField(max_length=100, null=True, verbose_name='도로명'),
        ),
        migrations.AlterField(
            model_name='account',
            name='si_do',
            field=models.CharField(max_length=30, null=True, verbose_name='시도명'),
        ),
        migrations.AlterField(
            model_name='account',
            name='si_gun_goo',
            field=models.CharField(max_length=30, null=True, verbose_name='시군구명'),
        ),
    ]
